Lab5_3973887764: KYP.o KWP.o main.o
	g++ KYP.o KWP.o main.o -o Lab5_3973887764
    
KWP.o: KWP.h Profit.h
	g++ -c KWP.cpp

KYP.o: KYP.h Profit.h
	g++ -c KYP.cpp
    
main.o: main.cpp
	g++ -c main.cpp
    
clean:
	rm *.o Lab*
